# Generated by Django 3.2.7 on 2022-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internshipname', models.CharField(max_length=150)),
                ('studid', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('phoneno', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Amount', models.CharField(max_length=150)),
                ('Duration', models.CharField(max_length=150)),
                ('Vaccancy', models.CharField(max_length=150)),
                ('Stipend', models.CharField(max_length=150)),
                ('post_date', models.CharField(max_length=150)),
                ('last_date', models.CharField(max_length=150)),
                ('Qualification', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=150)),
                ('photo', models.FileField(max_length=150, upload_to='')),
                ('date', models.CharField(max_length=150)),
                ('internshipid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='onliness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=150)),
                ('link', models.FileField(max_length=150, upload_to='')),
                ('date', models.CharField(max_length=150)),
                ('internshipid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='stafftask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=150)),
                ('photo', models.FileField(max_length=150, upload_to='')),
                ('date', models.CharField(max_length=150)),
                ('internshipid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('pass_year', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='taskupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=150)),
                ('staffid', models.FileField(max_length=150, upload_to='')),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
                ('phone_No', models.CharField(max_length=150)),
                ('Course', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
            ],
        ),
    ]
