# Generated by Django 4.1.7 on 2023-03-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('subject', models.FileField(max_length=150, upload_to='')),
                ('des', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='stud',
            name='image',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
